language: ruby
rvm:
  - 2.1.5

addons:
  code_climate:
    repo_token:

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql
  - redis-server

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER tiempolibre_rails WITH PASSWORD 'tiempolibre_rails';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS tiempolibre_rails_test;" -U postgres
  - psql -c "CREATE DATABASE tiempolibre_rails_test ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate test:prepare

script:
  - bundle exec rspec
  - bundle exec cucumber
  - bundle exec rubocop app spec features -R --format simple

notifications:
  email:
    recipients:
      - tiempolibre_rails-dev@wolox.com.ar

cache:
  bundler: true
